feat: increase size limit to 128k of return data
godwokenrises/godwoken-scripts pull request #135
Opened 2022-10-10 03:11 UTC by magicalne

2022-10-11 14:48 UTC, Flouse approved these changes

2022-10-12 10:35 UTC, Flouse requested changes
What about [validator_utils](https://github.com/magicalne/godwoken-scripts/blob/inc_ret_data/c/validator_utils.h#L47)？

2022-10-14 05:55 UTC, jjyr approved these changes

2022-10-24 05:44 UTC, Flouse commented
> What about [validator_utils](https://github.com/magicalne/godwoken-scripts/blob/inc_ret_data/c/validator_utils.h#L47)？

please check gw_call_receipt_t struct.
https://github.com/godwokenrises/godwoken-scripts/blob/master/c/validator_utils.h#L45-L49
@magicalne

2022-10-24 06:40 UTC, magicalne commented
> > What about [validator_utils](https://github.com/magicalne/godwoken-scripts/blob/inc_ret_data/c/validator_utils.h#L47)？
> 
> please check gw_call_receipt_t struct. https://github.com/godwokenrises/godwoken-scripts/blob/master/c/validator_utils.h#L45-L49 @magicalne

Done!

2022-10-24 06:47 UTC, jjyr approved these changes

2022-10-24 08:21 UTC, Flouse approved these changes

2022-10-24 09:08 UTC, zeroqn approved these changes

2022-10-24 10:32 UTC, jjyr approved these changes

2022-10-24 10:32 UTC, merged